"""added likes table

Revision ID: 22990b76548b
Revises: 
Create Date: 2025-08-20 15:28:00.242056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22990b76548b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('select_img', sa.String(length=250), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('select_img')

    # ### end Alembic commands ###
